### ISSUE TITLE
add a link to this paragraph in the gutenberg books

### ISSUE THREAD

**Issue by Haroenv** [pixelastic/gutenberg#1]
I'm not sure how much information you left in there, but the chapters seem to have ids in the html version of Guthenberg, maybe you could add a link to read from there? 

http://www.gutenberg.org/files/2097/2097-h/2097-h.htm#chap02 for example is the second chapter. Not sure how consistent that is though

**Comment by pixelastic** [comment]
Thanks for the idea, but as you suspected, the HTML versions of each book is slightly different on Gutenberg, meaning I don't think I'll have an id to link to for every book.

Additionally, Gutenberg here is just one of many potential sources (I would like to be able to extract data from `epub`/`mobi` files for examples) and the "meat" of the project is the front-end display. I don't think I want to have it linked to one specific source more than necessary.

But thanks for the idea, though :)

**Comment by Haroenv** [comment]
Makes sense. A canonical reference of books would be nice to have in this case (like there is for bibles)

**Comment by pixelastic** [comment]
What do you mean? Like a list of links to Sherlock Books?



On Mon, Jan 16, 2017 at 10:42am, Haroen Viaene < notifications@github.com [notifications@github.com] > wrote:
Makes sense. A canonical reference of books would be nice to have in this case (like there is for bibles)

**Comment by Haroenv** [comment]
Something like "this book, that chapter, that paragraph" so that you could continue reading there. But probably with all different editions etc it won't be easy

**Comment by pixelastic** [comment]
It should already have the book and chapter displayed at the bottom of each result. For paragraphs it's more tricky as yes, there might be differences between editions.

**Comment by Haroenv** [comment]
What could maybe be an option, is to make sure you have the order somewhere in the Algolia records, and then add buttons for load next and load previous part.

Or even remember the line of the read html file and linking to that again?
